name: lllmao
base: core24
version: 'vJanus-beta'
summary: Local Lightweight Language Model Assistant Orchestrator
description: |
  LLLMao is a Linux-native local AI workstation
  platform for Ollama-based conversational AI,
  semantic RAG, workspace intelligence,
  and multimodal workflows.

grade: devel
confinement: classic

apps:
  myownrtxchat:
    command: lllmao
    plugs:
      - home
      - network
      - network-bind
      - removable-media

parts:
  myownrtxchat:
    plugin: dump
    source: .
